### ISSUE TITLE
using loaded page

### ISSUE THREAD

**Issue by azgorov** [flole/CefSharp.AppDomain#1]
Hello,

I have tried to add some code after loading page for example:

browser.EvaluateScriptAsync("(function() { return document.title })();");
browser.ScreenshotAsync(true); 

When i add task,ContinueWith it just dies. 

I am testing with webapp.
Any idea why this can happen?

Best
Kalin

**Comment by flole** [comment]
Do you have an example code for me?

**Comment by azgorov** [comment]
I just get your code. And in place where you have

//Google has been loaded

```
        //Yay!
```

I have placed 

var t1 = browser.EvaluateScriptAsync("(function() { return document.title })();");

```
  var complete = t1.ContinueWith(t =>

  {

    if (!t.IsFaulted)

    {

      var response = t.Result;

    }

    _renderingFinishedSemaphore.Release();

  }, TaskScheduler.Default);
```

That is all. I have placed semaphore release inside continue with otherwise it just stops.

I have tried with all possible taskscheduler cases but nothing.

The same is if async task is not evaluatescript but just screenshot

var task = browser.ScreenshotAsync(true);

It just does not fires ContinueWith.

Even if I add

t1.Wait() 

Best

Kalin

**Comment by flole** [comment]
The IIS is looking for the Cef related files in its execution path, but the files are in the bin folder of the webapp.
I changed the Cef initialization according to this and set the paths manually. This works just fine for me.
I added your example to my repo and got "Google". Let me know if it also works for you.

Best regards
Florian

**Comment by azgorov** [comment]
This is working now but do you know if it is possible to return some value?
for example RenderSomething to return string (title for example) or Bitmap (if replace evalatescript with screenshot)

I tried but it seems that result in homecontroller is null.

Best
Kalin

**Comment by flole** [comment]
I just committed an update which will do exactly this. #2

An `TaskCompletionSource` is used to wait for the result from `EvaluateScript`. Unfortunately `RenderSomething` can't return a Task because a Task isn't serializable, but every object that is passed between the AppDomains needs to be serializable.

Best regards,
Florian

**Comment by azgorov** [comment]
Hmm strange,

I have exactly the same code only difference is that I try to send Bitmap(from screenshot) not string and it is not working. Bitmap is serializable too so i do not think that problem is there.

Thanks
Kalin

**Comment by flole** [comment]
When I change the ResultType from the `TaskCompletionSource` to Bitmap and use ScreenshotAsync instead of `EvaluateScriptAsync` it works fine.
![img](https://cloud.githubusercontent.com/assets/6204853/19105081/6ce9ae5c-8ae0-11e6-97cb-849843b7c2b7.png)

Here are the changed lines (You need to change the ReturnType of RenderSomething to Bitmap):

```
private TaskCompletionSource<Bitmap> _taskCompletionSource;

_taskCompletionSource = new TaskCompletionSource<Bitmap>();
_taskCompletionSource.Task.Wait();
return _taskCompletionSource.Task.Result;

var t1 = _browser.ScreenshotAsync(true);
var complete = t1.ContinueWith(t =>
{
    if (!t.IsFaulted)
    {
        var response = t.Result;
    }
    _taskCompletionSource?.TrySetFromTask(t);
}, TaskScheduler.Default);
```

In the HomeController of the Webapp you can save the resulting image:

```
Console.WriteLine("Render something in default AppDomain: ");
var res = renderer.RenderSomething();
res.Save("Z:\\Projekte\\img.png");
Console.WriteLine("Works!");
```

Best regards,
Florian

**Comment by azgorov** [comment]
Strange, maybe problem is somewhere in my environment as I get result with type

System.Runtime.Remoting.Proxies.__TransparentProxy and then trying to save it :

Type 'System.Drawing.Imaging.ImageFormat' in assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.

Best

Kalin

**Comment by flole** [comment]
Yeah that is strange.
As a workaround you could convert the bitmap to an byte array and pass this array between the appdomains

**Comment by azgorov** [comment]
Hello again,

Did you ever tried to deploy webapp somewhere?
I receive some really strange behavior (in my case amazon ec2 vm).
it works on my iis 8.5 windows 2012 but when i deploy 
it says: 

Could not load file or assembly 'CefSharp.BrowserSubprocess.Core.DLL' or one of its dependencies. The specified module could not be found.

If I "Enable 32bit apps" error is changed: Could not load file or assembly 'CefSharp.BrowserSubprocess.Core' or one of its dependencies. An attempt was made to load a program with an incorrect format.  which is normal i think as i use x64 everywhere.

All prerequirements seems fine - this mean VSRedis 2013 is installed and all files are in \bin forlder.

**Comment by flole** [comment]
Is Shadow-Copying enabled on your Amazon VM? It should be disabled to find all of its dependencies
